version: "3.7"

services:
  postgres:
    container_name: postgres-glamping
    image: postgres:latest
    environment:
      POSTGRES_DB: glamping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    expose:
      - "5432"

  glamping:
    container_name: glamping_service
    build: .
    environment:
      DB_URL: jdbc:postgresql://postgres-glamping:5432/glamping
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_LOG_LEVEL: DEBUG
      SERVER_PORT: 8080
    depends_on:
      - postgres
